In [2]:
import pandas as pd
import numpy as np

In [6]:
data = pd.Series([10,20,30,40],index =  ["A","B","C","D"])
print(data)

data = {
    "Name" : ["priyanshu","Jil","Akshar"],
    "Age" : [20,22,23],
    "Salary" : [10000,20000,40000]
}

df = pd.DataFrame(data)
print(df)

A    10
B    20
C    30
D    40
dtype: int64
        Name  Age  Salary
0  priyanshu   20   10000
1        Jil   22   20000
2     Akshar   23   40000

In [7]:
# 25/3/26

df = pd.read_csv("california_housing_test.csv")
print(df)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms
0       -122.05     37.37                  27         3885             661  \
1       -118.30     34.26                  43         1510             310
2       -117.81     33.78                  27         3589             507
3       -118.36     33.82                  28           67              15
4       -119.67     36.33                  19         1241             244
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                  23         1450             642
2996    -118.14     34.06                  27         5257            1082
2997    -119.70     36.30                  10          956             201
2998    -117.12     34.10                  40           96              14
2999    -119.63     34.42                  42         1765             263

      population  households  median_income  median_house_value
0           1537         606         6.6085              344700
1            809         277         3.5990              176500
2           1484         495         5.7934              270500
3             49          11         6.1359              330000
4            850         237         2.9375               81700
...          ...         ...            ...                 ...
2995        1258         607         1.1790              225000
2996        3496        1036         3.3906              237200
2997         693         220         2.2895               62000
2998          46          14         3.2708              162500
2999         753         260         8.5608              500001

[3000 rows x 9 columns]

In [8]:
df.head() # it will show first 5 values by default
# df.head(10) # it will show first 10 values

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27,3885,661,1537,606,6.6085,344700
1,-118.30,34.26,43,1510,310,809,277,3.5990,176500
2,-117.81,33.78,27,3589,507,1484,495,5.7934,270500
3,-118.36,33.82,28,67,15,49,11,6.1359,330000
4,-119.67,36.33,19,1241,244,850,237,2.9375,81700

In [9]:
df.tail()
# df.tail(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23,1450,642,1258,607,1.1790,225000
2996,-118.14,34.06,27,5257,1082,3496,1036,3.3906,237200
2997,-119.70,36.30,10,956,201,693,220,2.2895,62000
2998,-117.12,34.10,40,96,14,46,14,3.2708,162500
2999,-119.63,34.42,42,1765,263,753,260,8.5608,500001

In [10]:
df.info() # shows no of rows, columns, datatypes and missing values.
df.describe() # gives statistical summary.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   int64
 3   total_rooms         3000 non-null   int64
 4   total_bedrooms      3000 non-null   int64
 5   population          3000 non-null   int64
 6   households          3000 non-null   int64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   int64
dtypes: float64(3), int64(6)
memory usage: 211.1 KB

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [11]:
# df.to_csv("california_housing_test(1).csv")
# df.to_excel("california_housing_test(1).xlsx")
# this are the formats of exporting csv and excel files.

In [12]:
data = {
"Customer": ["Aman", "Priya", "Rahul", "Sneha", "Karan"],
"City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"],
"Revenue": [12000, 8000, 15000, 7000, 20000]
}
df = pd.DataFrame(data)
df

  Customer       City  Revenue
0     Aman      Delhi    12000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
3    Sneha  Bangalore     7000
4    Karan     Mumbai    20000

In [13]:
df["Revenue"] # selecting a column from the dataset

0    12000
1     8000
2    15000
3     7000
4    20000
Name: Revenue, dtype: int64

In [14]:
df[["Customer", "Revenue"]] # selecting multiple columns from the dataset

  Customer  Revenue
0     Aman    12000
1    Priya     8000
2    Rahul    15000
3    Sneha     7000
4    Karan    20000

In [15]:
df.loc[1] # it shows rows based on its index or row values.

Customer     Priya
City        Mumbai
Revenue       8000
Name: 1, dtype: object

In [16]:
df.loc[[0,1]] # it shows multiple rows at once in the same manner as above

  Customer    City  Revenue
0     Aman   Delhi    12000
1    Priya  Mumbai     8000

In [17]:
df.loc[1,"Revenue"]

8000

In [18]:
df.iloc[1,1] # it takes column index instead of column name because there might be very big names of columns

'Mumbai'

In [19]:
# Boolean filtering
# df["Revenue"] > 10000
df[df["Revenue"] > 10000]

# Query Data
# df.query("Revenue > 10000") # it works same as above with query method

  Customer    City  Revenue
0     Aman   Delhi    12000
2    Rahul   Delhi    15000
4    Karan  Mumbai    20000

In [20]:
df[(df["Revenue"] > 10000) & (df["City"] == "Delhi")]

  Customer   City  Revenue
0     Aman  Delhi    12000
2    Rahul  Delhi    15000

In [30]:
# 26/3/26

df.sort_values(by="Customer",ascending=True)

  Customer       City  Revenue
0     Aman      Delhi    12000
4    Karan     Mumbai    20000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
3    Sneha  Bangalore     7000

In [28]:
df.sort_values(by=["City","Revenue"],ascending=False)

  Customer       City  Revenue
4    Karan     Mumbai    20000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
0     Aman      Delhi    12000
3    Sneha  Bangalore     7000

In [ ]:
df.sort_values(by="Revenue")

df.sort_index() # it will sort according to index values if not sorted

  Customer       City  Revenue
0     Aman      Delhi    12000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
3    Sneha  Bangalore     7000
4    Karan     Mumbai    20000

In [ ]:
sorted_df = df.sort_values(by="Revenue")
# sorted_df
sorted_df.reset_index() # after sorting acc to revenue the index will be unsorted so we will reset index and give new index to all values which are sorted acc to revenue

   index Customer       City  Revenue
0      3    Sneha  Bangalore     7000
1      1    Priya     Mumbai     8000
2      0     Aman      Delhi    12000
3      2    Rahul      Delhi    15000
4      4    Karan     Mumbai    20000

In [ ]:
sorted_df.reset_index(drop=True) # it will drop the old indexes

  Customer       City  Revenue
0    Sneha  Bangalore     7000
1    Priya     Mumbai     8000
2     Aman      Delhi    12000
3    Rahul      Delhi    15000
4    Karan     Mumbai    20000

In [ ]:
df

  Customer       City  Revenue
0     Aman      Delhi    12000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
3    Sneha  Bangalore     7000
4    Karan     Mumbai    20000

In [ ]:
df.reindex([4,3,2,1,0]) # it allows us to reorder or redefine the index, it will not change any index for rows. It will just show in the order we have given

  Customer       City  Revenue
4    Karan     Mumbai    20000
3    Sneha  Bangalore     7000
2    Rahul      Delhi    15000
1    Priya     Mumbai     8000
0     Aman      Delhi    12000

In [55]:
# 27/3/26

data = {
    "Customer" : ["Aman","priya","rahul","sneha","psp"],
    "Age" : [25,np.nan,30,np.nan,10],
    "City" : ["Delhi",None,"Delhi","Bangalore","Bangalore"] # np.nan or none both will be replaced
}

df = pd.DataFrame(data)
print(df)

  Customer   Age       City
0     Aman  25.0      Delhi
1    priya   NaN       None
2    rahul  30.0      Delhi
3    sneha   NaN  Bangalore
4      psp  10.0  Bangalore

In [56]:
print(df.isnull())
print(df.isnull().sum())

   Customer    Age   City
0     False  False  False
1     False   True   True
2     False  False  False
3     False   True  False
4     False  False  False
Customer    0
Age         2
City        1
dtype: int64

In [59]:
# print(df.dropna(axis = 0, how = "any")) # if there is any NaN or None values in row then it will remove whole row
print(df.dropna(axis = 0, how = "all")) # if there are all NaN or None values in row then it will remove whole row

  Customer   Age       City
0     Aman  25.0      Delhi
1    priya   NaN  Bangalore
2    rahul  30.0      Delhi
3    sneha   NaN  Bangalore
4      psp  10.0  Bangalore

In [61]:
# print(df.dropna(axis = 1, how = "any")) # if there is any NaN or None values in column then it will remove whole column
print(df.dropna(axis = 1, how = "all")) # if there are all NaN or None values in column then it will remove whole column

  Customer   Age       City
0     Aman  25.0      Delhi
1    priya   NaN  Bangalore
2    rahul  30.0      Delhi
3    sneha   NaN  Bangalore
4      psp  10.0  Bangalore

In [ ]:
print(df["Age"].fillna(df["Age"].mean())) # it will fill all NaN or none values with the mean of all age values
print(df["Age"].fillna(df["Age"].median())) # it will fill all NaN or none values with the median of all age values

0    25.000000
1    21.666667
2    30.000000
3    21.666667
4    10.000000
Name: Age, dtype: float64

In [58]:
# 28/3/26

df["City"] = df["City"].fillna(df["City"].mode()[0]) # it replaces the categorical data nan/none values with the particular index of mode values 
df

  Customer   Age       City
0     Aman  25.0      Delhi
1    priya   NaN  Bangalore
2    rahul  30.0      Delhi
3    sneha   NaN  Bangalore
4      psp  10.0  Bangalore

In [47]:
df["City"] = df["City"].fillna("Unknown")
print(df)

  Customer       City  Revenue
0     Aman      Delhi    12000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
3    Sneha  Bangalore     7000
4    Karan     Mumbai    20000

In [64]:
df = df.fillna({
    "Age": df["Age"].mean(),
    "City": "Unknown"
})
print(df)

  Customer        Age       City
0     Aman  25.000000      Delhi
1    priya  21.666667  Bangalore
2    rahul  30.000000      Delhi
3    sneha  21.666667  Bangalore
4      psp  10.000000  Bangalore

In [ ]:
# 30/3/26

data = {
    "Customer": ["Aman", "Priya", "Aman", "Rahul","Aman"],
    "Sales": [500, 700, 500, 900,500]
}

df = pd.DataFrame(data)

df

  Customer  Sales
0     Aman    500
1    Priya    700
2     Aman    500
3    Rahul    900
4     Aman    500

In [11]:
df.drop_duplicates() # to remove the duplicate rows from the dataset

  Customer  Sales
0     Aman    500
1    Priya    700
3    Rahul    900

In [3]:
sales = pd.Series([100,120,130,110,115,500])

Q1 = sales.quantile(0.25)
Q3 = sales.quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = sales[(sales < lower) | (sales > upper)]

outliers

5    500
dtype: int64

In [4]:
mean = sales.mean()
std = sales.std()

z_scores = (sales - mean) / std

z_scores

0   -0.502667
1   -0.375677
2   -0.312182
3   -0.439172
4   -0.407425
5    2.037123
dtype: float64

In [6]:
data = {
    "Product": ["Pen", "Notebook", "Marker"],
    "Price": [10, 50, 20],
    "Qty": [100, 40, 60]
}

df = pd.DataFrame(data)

df

    Product  Price  Qty
0       Pen     10  100
1  Notebook     50   40
2    Marker     20   60

In [7]:
df["Revenue"] = df["Price"] * df["Qty"]
df

    Product  Price  Qty  Revenue
0       Pen     10  100     1000
1  Notebook     50   40     2000
2    Marker     20   60     1200

In [8]:
df["Price_with_tax"] = df["Price"].apply(lambda x : x * 2.137 )
df

    Product  Price  Qty  Revenue  Price_with_tax
0       Pen     10  100     1000           21.37
1  Notebook     50   40     2000          106.85
2    Marker     20   60     1200           42.74

In [12]:
df_numeric = df[["Price","Qty"]]
print(df_numeric)
# df_numeric.applymap(lambda x: x * 2) # this was used before but now it is only map and not applymap
df_numeric.map(lambda x: x * 2)

   Price  Qty
0     10  100
1     50   40
2     20   60

   Price  Qty
0     20  200
1    100   80
2     40  120

In [15]:
df["Revenue"] = df["Price"] * df["Qty"]

total_revenue = df["Revenue"].sum()

total_revenue

np.int64(4200)

In [16]:
#31/3/26

data = {
    "category" : ["Electronics","electronics","ELECTRONICS","Clothing"]
}

df = pd.DataFrame(data)

df["Category_Lower"] = df["category"].str.lower()
df["Category_Upper"] = df["category"].str.upper()

df

      category Category_Lower Category_Upper
0  Electronics    electronics    ELECTRONICS
1  electronics    electronics    ELECTRONICS
2  ELECTRONICS    electronics    ELECTRONICS
3     Clothing       clothing       CLOTHING

In [17]:
df["category_replace"] = df["category"].str.replace("Electronics","eLECTRONICS")
df

      category Category_Lower Category_Upper category_replace
0  Electronics    electronics    ELECTRONICS      eLECTRONICS
1  electronics    electronics    ELECTRONICS      electronics
2  ELECTRONICS    electronics    ELECTRONICS      ELECTRONICS
3     Clothing       clothing       CLOTHING         Clothing

In [21]:
df[df["category"].str.contains("thing",case=False)]

   category Category_Lower Category_Upper category_replace
3  Clothing       clothing       CLOTHING         Clothing

In [32]:
data = {
    "Name" : ["Priyanshu Patel","Jil Patel","Akshar Bhavsar"]
}

df = pd.DataFrame(data)
df["Split_Name"] = df["Name"].str.split(" ")
df

              Name          Split_Name
0  Priyanshu Patel  [Priyanshu, Patel]
1        Jil Patel        [Jil, Patel]
2   Akshar Bhavsar   [Akshar, Bhavsar]

In [39]:
data = {
    "Date" : ["2024-01-01","2024-2-15","2024-3-10"] # it is in the form of string data and not date format so we convert it to date format with pd.to_datetime function
    # "Date1" : [2024-1-1,2024-2-15,2024-3-10] 
}

df = pd.DataFrame(data)
# df.info() # it will give output as string for Date and int for Date1
df["Date"] = pd.to_datetime(df["Date"])
df

        Date
0 2024-01-01
1 2024-02-15
2 2024-03-10

In [41]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

df

        Date  Year  Month  Day
0 2024-01-01  2024      1    1
1 2024-02-15  2024      2   15
2 2024-03-10  2024      3   10

In [42]:
dates = pd.date_range(start="2024-01-01",end = "2024-1-7",freq="D")
dates

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07'],
              dtype='datetime64[us]', freq='D')

In [8]:
dates = pd.date_range(start="2024-01-01",end = "2024-12-31",freq="ME")
dates

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31'],
              dtype='datetime64[us]', freq='ME')

In [20]:
dates = pd.date_range(start="2024-3-30",end = "2037-3-31",freq="YE")
dates

DatetimeIndex(['2024-12-31', '2025-12-31', '2026-12-31', '2027-12-31',
               '2028-12-31', '2029-12-31', '2030-12-31', '2031-12-31',
               '2032-12-31', '2033-12-31', '2034-12-31', '2035-12-31',
               '2036-12-31'],
              dtype='datetime64[us]', freq='YE-DEC')

In [24]:
data = {
    "Start_Date" : ["2023-1-1","2023-6-1"],
    "End_Date" : ["2024-1-1","2024-6-1"]
}

df = pd.DataFrame(data)

df["Start_Date"] = pd.to_datetime(df["Start_Date"])
df["End_Date"] = pd.to_datetime(df["End_Date"])

df["Tenure_Days"] = (df["End_Date"] - df["Start_Date"]).dt.days
df

  Start_Date   End_Date  Tenure_Days
0 2023-01-01 2024-01-01          365
1 2023-06-01 2024-06-01          366