In [2]:
import pandas as pd
import numpy as np

In [4]:
data = {
"Customer": ["Aman", "Priya", "Rahul", "Sneha", "Karan"],
"City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"],
"Revenue": [12000, 8000, 15000, 7000, 20000]
}
df = pd.DataFrame(data)

In [ ]:
# Questions from Pandas_2.ipynb - Colab file

# 1) Display the entire dataset.

df

  Customer       City  Revenue
0     Aman      Delhi    12000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
3    Sneha  Bangalore     7000
4    Karan     Mumbai    20000

In [5]:
# 2) Select only the Revenue column.

df["Revenue"]

0    12000
1     8000
2    15000
3     7000
4    20000
Name: Revenue, dtype: int64

In [6]:
# 3) Select the Customer and Revenue columns together.

df[["Customer","Revenue"]]

  Customer  Revenue
0     Aman    12000
1    Priya     8000
2    Rahul    15000
3    Sneha     7000
4    Karan    20000

In [7]:
# 4) Using loc, display the second row of the dataset.

df.loc[1]

Customer     Priya
City        Mumbai
Revenue       8000
Name: 1, dtype: object

In [9]:
# 5) Using iloc, display the third row of the dataset.

df.iloc[2]

Customer    Rahul
City        Delhi
Revenue     15000
Name: 2, dtype: object

In [13]:
# 6) Using loc, retrieve the Revenue value of Rahul.

df.loc[2,"Revenue"]

15000

In [14]:
# 7) Filter the dataset to show customers whose Revenue is greater than 10000.

df[df["Revenue"] > 10000]

  Customer    City  Revenue
0     Aman   Delhi    12000
2    Rahul   Delhi    15000
4    Karan  Mumbai    20000

In [15]:
# 8) Display customers who belong to Mumbai.

df[df["City"] == "Mumbai"]

  Customer    City  Revenue
1    Priya  Mumbai     8000
4    Karan  Mumbai    20000

In [18]:
# 9) Sort the dataset by Revenue in ascending order.

df.sort_values("Revenue")

  Customer       City  Revenue
3    Sneha  Bangalore     7000
1    Priya     Mumbai     8000
0     Aman      Delhi    12000
2    Rahul      Delhi    15000
4    Karan     Mumbai    20000

In [8]:
# Questions from Gmail file

# 1) Create a DataFrame with columns: Name, Age, City, Salary

data = {
    "Name" : ["A","B","C","D"],
    "Age" : [20,21,22,23],
    "City" : ["Ahmedabad","Mumbai","Pune","Hyderabad"],
    "Salary" : [12000,13000,14000,15000]
}

df = pd.DataFrame(data)

# Tasks:
# • Display only the Age column
df["Age"]

# • Display Name and Salary together
df[["Name","Salary"]]

  Name  Salary
0    A   12000
1    B   13000
2    C   14000
3    D   15000

In [15]:
# 2) Using the same dataset:
# • Select the 3rd row using iloc
df.iloc[2]

# • Select the Salary of the 2nd row using loc
df.loc[1,"Salary"]

13000

In [19]:
# 3) Filter the dataset:
# • Show rows where Salary > 13000
df[df["Salary"] > 13000]

# • Show rows where City is "Pune"
df[df["City"] == "Pune"]

  Name  Age  City  Salary
2    C   22  Pune   14000

In [27]:
# 4) Apply multiple conditions:
# • Salary > 40000 AND City = "Mumbai"
df[(df["Salary"] > 13000) & (df["City"] == "Hyderabad")]

  Name  Age       City  Salary
3    D   23  Hyderabad   15000

In [ ]:
# 5) Sort the dataset:
# • Sort by Salary in ascending order
df.sort_values("Salary")
# • Sort by Salary in descending order
sorted = df.sort_values("Salary",ascending=False)
sorted

  Name  Age       City  Salary
3    D   23  Hyderabad   15000
2    C   22       Pune   14000
1    B   21     Mumbai   13000
0    A   20  Ahmedabad   12000

In [ ]:
# 6) After sorting:
# • Reset the index
sorted.reset_index()
# • Remove the old index
new_sorted = sorted.reset_index(drop=True) # to drop old indexes and save the new ones we need to save it in another variable
new_sorted

  Name  Age       City  Salary
0    D   23  Hyderabad   15000
1    C   22       Pune   14000
2    B   21     Mumbai   13000
3    A   20  Ahmedabad   12000

In [ ]:
print(sorted.loc[1])
print(new_sorted.loc[1])

Name           B
Age           21
City      Mumbai
Salary     13000
Name: 1, dtype: object
Name          C
Age          22
City       Pune
Salary    14000
Name: 1, dtype: object

In [82]:
# 7) Create a dataset with missing values in Age.

data = {
    "Name" : ["A","B","C","D"],
    "Age" : [20,np.nan,22,None],
    "City" : ["Ahmedabad",None,"Pune","Hyderabad"],
    "Salary" : [12000,13000,14000,15000]
}

df = pd.DataFrame(data)

# Tasks:
# • Detect missing values using isnull()
print(df.isnull())
# • Count missing values per column
print(df.isnull().sum())

    Name    Age   City  Salary
0  False  False  False   False
1  False   True   True   False
2  False  False  False   False
3  False   True  False   False
Name      0
Age       2
City      1
Salary    0
dtype: int64

In [78]:
# 8) Using the same dataset:
# • Drop rows with missing values
# print(df.dropna(axis = 0, how = "any"))
# • Drop columns with missing values
# print(df.dropna(axis = 1, how = "any"))
df

  Name   Age       City  Salary
0    A  20.0  Ahmedabad   12000
1    B   NaN     Mumbai   13000
2    C  22.0       Pune   14000
3    D   NaN  Hyderabad   15000

In [84]:
# 9) Fill missing values:
# • Replace missing Age with mean
print(df["Age"].fillna(df["Age"].mean()))
# • Replace missing City with "Unknown"
df["City"] = df["City"].fillna("Unknown")
df

0    20.0
1    21.0
2    22.0
3    21.0
Name: Age, dtype: float64

  Name   Age       City  Salary
0    A  20.0  Ahmedabad   12000
1    B   NaN    Unknown   13000
2    C  22.0       Pune   14000
3    D   NaN  Hyderabad   15000