In [1]:
import pandas as pd
import numpy as np

In [4]:
data = {
"Customer": ["Aman", "Priya", "Rahul", "Sneha", "Karan"],
"City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai"],
"Revenue": [12000, 8000, 15000, 7000, 20000]
}
df = pd.DataFrame(data)

In [ ]:
# Questions from Pandas_2.ipynb - Colab file

# 1) Display the entire dataset.

df

  Customer       City  Revenue
0     Aman      Delhi    12000
1    Priya     Mumbai     8000
2    Rahul      Delhi    15000
3    Sneha  Bangalore     7000
4    Karan     Mumbai    20000

In [5]:
# 2) Select only the Revenue column.

df["Revenue"]

0    12000
1     8000
2    15000
3     7000
4    20000
Name: Revenue, dtype: int64

In [6]:
# 3) Select the Customer and Revenue columns together.

df[["Customer","Revenue"]]

  Customer  Revenue
0     Aman    12000
1    Priya     8000
2    Rahul    15000
3    Sneha     7000
4    Karan    20000

In [7]:
# 4) Using loc, display the second row of the dataset.

df.loc[1]

Customer     Priya
City        Mumbai
Revenue       8000
Name: 1, dtype: object

In [9]:
# 5) Using iloc, display the third row of the dataset.

df.iloc[2]

Customer    Rahul
City        Delhi
Revenue     15000
Name: 2, dtype: object

In [13]:
# 6) Using loc, retrieve the Revenue value of Rahul.

df.loc[2,"Revenue"]

15000

In [14]:
# 7) Filter the dataset to show customers whose Revenue is greater than 10000.

df[df["Revenue"] > 10000]

  Customer    City  Revenue
0     Aman   Delhi    12000
2    Rahul   Delhi    15000
4    Karan  Mumbai    20000

In [15]:
# 8) Display customers who belong to Mumbai.

df[df["City"] == "Mumbai"]

  Customer    City  Revenue
1    Priya  Mumbai     8000
4    Karan  Mumbai    20000

In [18]:
# 9) Sort the dataset by Revenue in ascending order.

df.sort_values("Revenue")

  Customer       City  Revenue
3    Sneha  Bangalore     7000
1    Priya     Mumbai     8000
0     Aman      Delhi    12000
2    Rahul      Delhi    15000
4    Karan     Mumbai    20000

In [ ]:
# Questions from Gmail file sent in whatsapp

# 1) Create a DataFrame with columns: Name, Age, City, Salary

data = {
    "Name" : ["A","B","C","D"],
    "Age" : [20,21,22,23],
    "City" : ["Ahmedabad","Mumbai","Pune","Hyderabad"],
    "Salary" : [12000,13000,14000,15000]
}

df = pd.DataFrame(data)

# Tasks:
# • Display only the Age column
df["Age"]

# • Display Name and Salary together
df[["Name","Salary"]]

  Name  Salary
0    A   12000
1    B   13000
2    C   14000
3    D   15000

In [15]:
# 2) Using the same dataset:
# • Select the 3rd row using iloc
df.iloc[2]

# • Select the Salary of the 2nd row using loc
df.loc[1,"Salary"]

13000

In [19]:
# 3) Filter the dataset:
# • Show rows where Salary > 13000
df[df["Salary"] > 13000]

# • Show rows where City is "Pune"
df[df["City"] == "Pune"]

  Name  Age  City  Salary
2    C   22  Pune   14000

In [27]:
# 4) Apply multiple conditions:
# • Salary > 40000 AND City = "Mumbai"
df[(df["Salary"] > 13000) & (df["City"] == "Hyderabad")]

  Name  Age       City  Salary
3    D   23  Hyderabad   15000

In [ ]:
# 5) Sort the dataset:
# • Sort by Salary in ascending order
df.sort_values("Salary")
# • Sort by Salary in descending order
sorted = df.sort_values("Salary",ascending=False)
sorted

  Name  Age       City  Salary
3    D   23  Hyderabad   15000
2    C   22       Pune   14000
1    B   21     Mumbai   13000
0    A   20  Ahmedabad   12000

In [ ]:
# 6) After sorting:
# • Reset the index
sorted.reset_index()
# • Remove the old index
new_sorted = sorted.reset_index(drop=True) # to drop old indexes and save the new ones we need to save it in another variable
new_sorted

  Name  Age       City  Salary
0    D   23  Hyderabad   15000
1    C   22       Pune   14000
2    B   21     Mumbai   13000
3    A   20  Ahmedabad   12000

In [ ]:
print(sorted.loc[1])
print(new_sorted.loc[1])

Name           B
Age           21
City      Mumbai
Salary     13000
Name: 1, dtype: object
Name          C
Age          22
City       Pune
Salary    14000
Name: 1, dtype: object

In [82]:
# 7) Create a dataset with missing values in Age.

data = {
    "Name" : ["A","B","C","D"],
    "Age" : [20,np.nan,22,None],
    "City" : ["Ahmedabad",None,"Pune","Hyderabad"],
    "Salary" : [12000,13000,14000,15000]
}

df = pd.DataFrame(data)

# Tasks:
# • Detect missing values using isnull()
print(df.isnull())
# • Count missing values per column
print(df.isnull().sum())

    Name    Age   City  Salary
0  False  False  False   False
1  False   True   True   False
2  False  False  False   False
3  False   True  False   False
Name      0
Age       2
City      1
Salary    0
dtype: int64

In [78]:
# 8) Using the same dataset:
# • Drop rows with missing values
# print(df.dropna(axis = 0, how = "any"))
# • Drop columns with missing values
# print(df.dropna(axis = 1, how = "any"))
df

  Name   Age       City  Salary
0    A  20.0  Ahmedabad   12000
1    B   NaN     Mumbai   13000
2    C  22.0       Pune   14000
3    D   NaN  Hyderabad   15000

In [84]:
# 9) Fill missing values:
# • Replace missing Age with mean
print(df["Age"].fillna(df["Age"].mean()))
# • Replace missing City with "Unknown"
df["City"] = df["City"].fillna("Unknown")
df

0    20.0
1    21.0
2    22.0
3    21.0
Name: Age, dtype: float64

  Name   Age       City  Salary
0    A  20.0  Ahmedabad   12000
1    B   NaN    Unknown   13000
2    C  22.0       Pune   14000
3    D   NaN  Hyderabad   15000

In [94]:
# Questions from Pandas_3.ipynb file
# This set covers:
# • DataFrame creation  
# • Selection (loc, iloc)  
# • Filtering  
# • Sorting  
# • Missing values  
# • Duplicates  
# • Outliers  
# • Column transformations  

# 1) Create a DataFrame with columns:
# Name, Age, City, Salary

data = pd.DataFrame({
   "Name" : ["Priya","Raju","Krish","Krisha"],
   "Age" : [20,21,22,np.NaN],
   "City" : ["Ahmedabad","Mehsana","Rajkot",None],
   "Salary" : [10000,20000,30000,40000]
})

# Tasks:
# • Display only the Age column  
data["Age"]
# • Display Name and Salary together
data[["Name","Salary"]]

     Name  Salary
0   Priya   10000
1    Raju   20000
2   Krish   30000
3  Krisha   40000

In [70]:
# 2) Using the same dataset:

# • Select the 3rd row using **iloc**
data.iloc[2]
# • Select the Salary of the 2nd row using **loc**
data.loc[1]

Name         Raju
Age          21.0
City      Mehsana
Salary      20000
Name: 1, dtype: object

In [71]:
# 3) Filter the dataset:

# • Show rows where Salary > 30000
data[data["Salary"] > 30000]
# • Show rows where City is "Mehsana"
data[data["City"] == "Mehsana"]

   Name   Age     City  Salary
1  Raju  21.0  Mehsana   20000

In [72]:
# 4) Apply multiple conditions:

# • Salary > 10000 AND City = "Rajkot"
data[(data["Salary"] > 10000) & (data["City"] == "Rajkot")]

    Name   Age    City  Salary
2  Krish  22.0  Rajkot   30000

In [73]:
# 5) Sort the dataset:

# • Sort by Salary in ascending order
data.sort_values("Salary")
# • Sort by Salary in descending order
sorted = data.sort_values("Salary",ascending=False)
sorted

     Name   Age       City  Salary
3  Krisha   NaN       None   40000
2   Krish  22.0     Rajkot   30000
1    Raju  21.0    Mehsana   20000
0   Priya  20.0  Ahmedabad   10000

In [74]:
# 6) After sorting:

# • Reset the index
sorted.reset_index() 
# • Remove the old index
sorted.reset_index(drop=True)

     Name   Age       City  Salary
0  Krisha   NaN       None   40000
1   Krish  22.0     Rajkot   30000
2    Raju  21.0    Mehsana   20000
3   Priya  20.0  Ahmedabad   10000

In [75]:
# 7) Create a dataset with missing values in Age.

# Tasks:

# • Detect missing values using isnull()
data.isnull()
# • Count missing values per column
data.isnull().sum()

Name      0
Age       1
City      1
Salary    0
dtype: int64

In [79]:
# 8) Using the same dataset:

# • Drop rows with missing values  
data = data.dropna(axis=0, how='any')
# • Drop columns with missing values
data = data.dropna(axis=1, how='any')
data

    Name   Age       City  Salary
0  Priya  20.0  Ahmedabad   10000
1   Raju  21.0    Mehsana   20000
2  Krish  22.0     Rajkot   30000

In [95]:
# 9) Fill missing values:

# • Replace missing Age with mean
data["Age"] = data["Age"].fillna(data["Age"].mean())
# • Replace missing City with "Unknown"
data["City"] = data["City"].fillna("Unknown")
data

     Name   Age       City  Salary
0   Priya  20.0  Ahmedabad   10000
1    Raju  21.0    Mehsana   20000
2   Krish  22.0     Rajkot   30000
3  Krisha  21.0    Unknown   40000

In [98]:
# 10) Create a dataset with duplicate rows.
data1 = pd.DataFrame({
   "Name" : ["Priya","Krisha","Krisha"],
   "Age" : [20,22,22],
   "City" : ["Ahmedabad","Rajkot","Rajkot"],
   "Salary" : [10000,30000,30000]
})
# Tasks:
# • Identify duplicates
data1.duplicated()
# • Remove duplicate rows
data1.drop_duplicates() 
data1

     Name  Age       City  Salary
0   Priya   20  Ahmedabad   10000
1  Krisha   22     Rajkot   30000
2  Krisha   22     Rajkot   30000

In [103]:
# 11) Create a Sales column:
# [100, 120, 110, 115, 500]
Sales = pd.Series([100, 120, 115, 500])

# Tasks:
# • Detect outliers using IQR method
Q1 = Sales.quantile(0.25)
Q3 = Sales.quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = Sales[(Sales < lower) | (Sales > upper)]
outliers

3    500
dtype: int64

In [ ]:
# 12) Using the same sales data:

# • Calculate Z-score for each value  
mean = Sales.mean()
std = Sales.std()

z_scores = (Sales - mean) / std

z_scores
# • Identify values where Z-score > 2 
z_scores[z_scores > 2]

3    1.498565
dtype: float64

In [110]:
# 13) Create a dataset:
# Product, Price, Quantity

data2 = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Smartwatch"],
    "Price": [50000, 20000, 15000, 3000, 7000],
    "Quantity": [5, 10, 7, 15, 8]
})

# Tasks:
# • Create new column Revenue = Price * Quantity
data2["Revenue"] = data2["Price"] * data2["Quantity"]
# • Calculate total revenue
data2["Revenue"].sum()

656000

In [114]:
# 14) Use apply() and lambda:
# • Increase all prices by 10%  
data2["Price_With_Tax"] = data2["Price"].apply(lambda x: x + (x * 0.1))
# • Create a new column Discounted Price = Price - 10%
data2["Discounted_Price"] = data2["Price"].apply(lambda x: x - (x * 0.1))
data2

      Product  Price  Quantity  Revenue  Price_With_Tax  Discounted_Price
0      Laptop  50000         5   250000         55000.0           45000.0
1      Mobile  20000        10   200000         22000.0           18000.0
2      Tablet  15000         7   105000         16500.0           13500.0
3  Headphones   3000        15    45000          3300.0            2700.0
4  Smartwatch   7000         8    56000          7700.0            6300.0

In [ ]:
# Final Integrated Question (Important)

# 15) Mini Data Cleaning & Analysis Task

# Create a dataset:
# Customer, Age, City, Price, Quantity
# Include:
# • Missing values in Age and City  
# • Duplicate rows  
data3 = pd.DataFrame({
    "Customer": ["Amit", "Riya", "Karan", "Neha", "Riya"],
    "Age": [25, np.nan, 30, 22, np.nan],
    "City": ["Ahmedabad", "Surat", None, "Rajkot", "Surat"],
    "Price": [1000, 2000, 1500, 1800, 2000],
    "Quantity": [2, 3, 1, 4, 3]
})

# Tasks:
# 1 Clean missing values  
#    • Replace Age with mean
data3["Age"] = data3["Age"].fillna(data3["Age"].mean())
#    • Replace City with "Unknown"
data3["City"] = data3["City"].fillna("Unknown")

# 2 Remove duplicate rows  
non_dup_data = data3.drop_duplicates()
non_dup_data
# 3 Create new column:  
#    Revenue = Price * Quantity
data3["Revenue"] = data3["Price"] * data3["Quantity"]
data3
# 4 Filter rows where Revenue > 5000  
data3[data3["Revenue"] > 5000]

# 5 Sort the dataset by Revenue in descending order 
sorted = data3.sort_values(by="Revenue",ascending=False)

# 6 Reset the index  
sorted.reset_index()

# 7 Identify any outliers in Revenue using IQR method
Q1 = data3["Revenue"].quantile(0.25)
Q3 = data3["Revenue"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = data3["Revenue"][(data3["Revenue"] < lower) | (data3["Revenue"] > upper)] # here we cannot use normal "or" because it gives error as "or" only checks true_false for 1 time but here in series we need to check it again and again so we use "|" and not "or". 
outliers

Series([], Name: Revenue, dtype: int64)

In [5]:
# Questions from Pandas_4.ipynb - colab.pdf

# This set covers:
# • String operations (str.lower, str.upper, replace, contains, split)
# • Date-time handling (to_datetime, dt extraction, date_range)
# • Real-world data cleaning scenarios

# 1) Create a DataFrame:
# Name = ["Aman Sharma", "Priya Patel", "Rahul Verma"]
data = pd.DataFrame({
    "Name" : ["Aman Sharma", "Priya Patel", "Rahul Verma"]
    })
data
# Tasks:

# • Convert all names to lowercase
data["Name_Lower"] = data["Name"].str.lower()
# • Convert all names to uppercase
data["Name_Upper"] = data["Name"].str.upper()
data

          Name   Name_Lower   Name_Upper
0  Aman Sharma  aman sharma  AMAN SHARMA
1  Priya Patel  priya patel  PRIYA PATEL
2  Rahul Verma  rahul verma  RAHUL VERMA

In [ ]:
# 2) Using the same dataset:

# • Split names into first and last names
data["Name_Split"] = data["Name"].str.split(" ")
data
# • Store them in two separate columns
data[["First_Name","Last_Name"]] = data["Name"].str.split(" ",expand = True)
data
# df["First_Name"] = data["Name"].str[0] # If there is a middle name too then we can use this and the next line to store only the first and last name
# df["Last_Name"] = data["Name"].str[-1]

          Name   Name_Lower   Name_Upper      Name_Split First_Name Last_Name
0  Aman Sharma  aman sharma  AMAN SHARMA  [Aman, Sharma]       Aman    Sharma
1  Priya Patel  priya patel  PRIYA PATEL  [Priya, Patel]      Priya     Patel
2  Rahul Verma  rahul verma  RAHUL VERMA  [Rahul, Verma]      Rahul     Verma

In [ ]:
# 3) Create a column:

# Category = ["Electronics", "ELECTRONICS", "Clothing"]
data["Category"] = ["Electronics", "ELECTRONICS", "Clothing"]
data
# Tasks:

# • Normalize all values to lowercase
data["Category"].str.lower()
# • Count how many times "electronics" appears
data["Category"].str.contains("electronics",case=False).sum()
# data["Category"].str.count("Electronics")
# data["Category"].str.count("lectronics")

2

In [ ]:
# 4) Create a column:

# Product = ["Phone-123", "Laptop-456", "Tablet-789"]
data["Product"] = ["Phon1e-123", "Laptop-456", "Tablet-789"]
# Tasks:

# • Remove numbers using str.replace()
data["Product"] = data["Product"].str.replace(r"\d+","",regex=True)
data
# • Keep only product names

,Name,Name_Lower,Name_Upper,Name_Split,First_Name,Last_Name,Category,Product
0,Aman Sharma,aman sharma,AMAN SHARMA,"[Aman, Sharma]",Aman,Sharma,Electronics,Phone-
1,Priya Patel,priya patel,PRIYA PATEL,"[Priya, Patel]",Priya,Patel,ELECTRONICS,Laptop-
2,Rahul Verma,rahul verma,RAHUL VERMA,"[Rahul, Verma]",Rahul,Verma,Clothing,Tablet-

In [32]:
# 5) Create a column:

# Email = ["aman@gmail.com", "priya@yahoo.com", "rahul@gmail.com"]
data["Email"] = ["aman@gmail.com", "priya@yahoo.com", "rahul@gmail.com"]

# Tasks:
# • Filter only Gmail users using str.contains()
data["Email"][data["Email"].str.contains("gmail.com",case=False)]

0     aman@gmail.com
2    rahul@gmail.com
Name: Email, dtype: object

In [36]:
# 6) Create a column:

# Text = ["apple orange", "banana mango", "grape apple"]
data["Text"] = ["apple orange", "banana mango", "grape apple"]

# Tasks:
# • Check which rows contain the word "apple"
data["Text"].str.contains("apple")

# • Return only those rows
data["Text"][data["Text"].str.contains("apple")]

0    apple orange
2     grape apple
Name: Text, dtype: object

In [41]:
# 7) Create a column:

# City = ["Delhi", "Mumbai", None, "Bangalore"]
data["City"] = ["Delhi", None, "Bangalore"]

# Tasks:
# • Replace missing values with "Unknown"
data["City"] = data["City"].fillna("Unknown")
# • Convert all values to uppercase
data["City"].str.upper()

0        DELHI
1      UNKNOWN
2    BANGALORE
Name: City, dtype: object

In [48]:
# 8) Create a column:

# Date = ["2024-01-01", "2024-02-15", "2024-03-10"]
data["Date"] = ["2024-01-01", "2024-02-15", "2024-03-10"]

# Tasks:

# • Convert the column to datetime
data["Date"] = pd.to_datetime(data["Date"])
data["Date"].info()
# • Extract year and month

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: Date
Non-Null Count  Dtype
--------------  -----
3 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 156.0 bytes

In [ ]:
# 9) Using the same dataset:

# • Extract only the day
data["Date"].dt.day
data["Date"]
# • Create a new column "Day_Name" (optional: weekday)
data["Day_Name"] = data["Date"].dt.day_name()
data["Day_Name"]
data

,Name,Name_Lower,Name_Upper,Name_Split,First_Name,Last_Name,Category,Product,Email,Text,City,Date,Day,Day_Name
0,Aman Sharma,aman sharma,AMAN SHARMA,"[Aman, Sharma]",Aman,Sharma,Electronics,Phone-,aman@gmail.com,apple orange,Delhi,2024-01-01,1,Monday
1,Priya Patel,priya patel,PRIYA PATEL,"[Priya, Patel]",Priya,Patel,ELECTRONICS,Laptop-,priya@yahoo.com,banana mango,Unknown,2024-02-15,15,Thursday
2,Rahul Verma,rahul verma,RAHUL VERMA,"[Rahul, Verma]",Rahul,Verma,Clothing,Tablet-,rahul@gmail.com,grape apple,Bangalore,2024-03-10,10,Sunday

In [16]:
# 10) Create a date range from:

# Start = "2024-01-01"
# End = "2024-01-05"


# Tasks:
# • Generate dates using pd.date_range()
dates = pd.date_range(start="2024-01-01",end = "2028-12-31",freq="YS")
dates
# • Convert it into a DataFrame
# data = {
#     "Start_Date" : ["2023-1-1","2023-6-1"],
#     "End_Date" : ["2024-1-1","2024-6-1"]
# }

# df["Start_Date"] = pd.to_datetime("2024-1-1")
# df["End_Date"] = pd.to_datetime("2024-1-5")

DatetimeIndex(['2024-01-01', '2025-01-01', '2026-01-01', '2027-01-01',
               '2028-01-01'],
              dtype='datetime64[ns]', freq='AS-JAN')

In [ ]:
# 11) Create a dataset:

# Start_Date = ["2023-01-01", "2023-06-01"]
# End_Date = ["2024-01-01", "2024-06-01"]

# Tasks:

# • Convert both columns to datetime
# • Calculate tenure in days

In [ ]:
# 12) Create a dataset:

# Date = ["2024-01-01", "invalid", "2024-03-10"]

# Tasks:

# • Convert to datetime using errors="coerce"
# • Identify invalid dates

In [ ]:
# 13) Create a dataset:

# Product = ["Mobile Phone", "Laptop", "Phone Case"]

# Tasks:

# • Filter rows where the word "Phone" exists
# • Ignore case sensitivity

In [ ]:
# 14) Create a dataset:

# Full_Name = ["Aman Sharma", "Priya Patel", "Rahul Verma"]

# Tasks:

# • Extract only last names
# • Create a new column "Last_Name"

In [ ]:
# 15) Data Cleaning + Time Analysis
# Create a dataset:
# Customer, Category, Start_Date, End_Date

# Include:
# • Mixed case category values
# • Missing values in Category
# • Date columns as strings

# Tasks:
# 1 Clean Category column
# • Convert to lowercase
# • Replace missing values with "unknown"

# 2 Convert Start_Date and End_Date to datetime

# 3 Calculate tenure in days

# 4 Extract Year and Month from Start_Date

# 5 Filter customers with tenure > 200 days

# 6 Identify rows where Category contains "electronics"

In [ ]:
# Pandas_5

# 1) Tasks : 
# Perform inner merge  
# Perform left merge  
# Perform outer merge  
# Compare number of rows in each result 
 
customers = df.DataFrame({
    "Customer_Id" : [1,2,3],
    "Name" : ["Aman","Priya","Rahul"]
})

orders = df.DataFrame({
    "Customer_Id" : [1,2,4],
    "Amount" : [500,700,300]
})

# Perform inner merge  
inner_row = pd.merge(customers,orders,how="inner",on="Customer_Id")

# Perform left merge  
pd.merge(customers,orders,how="left",on="Customer_Id")

# Perform outer merge  
pd.merge(customers,orders,how="outer",on="Customer_Id")

# Compare number of rows in each result